@startuml

' ===Classes de localização===

class Regiao {
  -id: Long
  -nome: String
}

class Estado {
  -id: Long
  -nome: String
  -sigla: String
}

class Cidade {
  -id: Long
  -nome: String
}

class Endereco {
  -id: Long
  -cep: String
  -logradouro: String
  -numero: String
  -complemento: String
}

' ===Usuário===

class Usuario {
  -id: Long
  -cpf: String
}

class Capacete {
  -marca: String
  -modelo: String
  -tamanho: String
}

' === Carrinho ===

class Carrinho {
  -id: Long
  -dataCriacao: Date
  -status: String
}

class ItemCarrinho {
  -id: Long
  -quantidade: int
}

' === Pedido ===

class Pedido {
  -id: Long
  -data: Date
  -status: String
}

class ItemPedido {
  -id: Long
  -quantidade: int
  -subtotal: BigDecimal
}

class Pagamento {
  -id: Long
  -valor: BigDecimal
  -metodo: String
  -status: String
}

class Cor {
  -nome: String
  -hexadecimal: String
}

enum Tamanho {
  +CINQUENTA_DOIS:int
  +CINQUENTA_QUATRO:int
  +CINQUENTA_SEIS:int
  +CINQUENTA_OITO:int
  +SESSENTA:int
  +SESSENTA_DOIS:int
}

enum Sexo {
  +MASCULINO:int
  +FEMININO:int
  +UNISEX:int
}

class Modelo {
  -nome: String
}

class Marca {
  -nome: String 
}

class Fabricante {
  -cnpj: String
  -razaoSocial: String
}

class Pessoa {
  -nome: String
  -email: String
}

class Telefone {
  -codigoPais: String
  -codigoArea: String 
  -numero: String
}

' === Relações ===

Endereco "*" --> "1" Cidade
Cidade "*" --> "1" Estado
Estado "*" --> "1" Regiao

Usuario "1" -- "1" Carrinho
Carrinho "1" -- "*" ItemCarrinho
ItemCarrinho "*" -- "1" Capacete

Usuario "1" -- "*" Pedido
Pedido "1" -- "*" ItemPedido
ItemPedido "*" -- "1" Capacete

Pedido "1" *-- "1" Pagamento
Capacete "*" --> "1" Modelo
Modelo "*" --> "1" Marca
Capacete "*" --> "*" Cor
Capacete "*" --> "1" Fabricante
Capacete "*" --> "1" Tamanho
Capacete "*" --> "1" Sexo

Fabricante --|> Pessoa
Usuario --|> Pessoa
Pessoa "1" *--> "*" Endereco
Pessoa "1" *--> "*" Telefone

@enduml